Framework.AddRoute(HomeController, 'home', 'views/home.html');
Framework.AddRoute(AboutController, 'about', 'views/about.html');
Framework.AddRoute(AccountController, 'account', 'views/account.html');
Framework.AddRoute(AddPetController, 'add-pet', 'views/add-pet.html');
Framework.AddRoute(FriendAccountController, 'friend-account', 'views/friend-account.html');
Framework.AddRoute(PlaygroundController, 'playground', 'views/playground.html');
Framework.AddRoute(RegisterController, 'register', 'views/register.html');
Framework.AddRoute(YourFriendsController, 'your-friends', 'views/your-friends.html');
Framework.AddRoute(YourPetsController, 'your-pets', 'views/your-pets.html');
Framework.Initialize();